#
#  Makefile for IPv6SuiteWithINET
#
#  ** This file was automatically generated by the command:
#  opp_makemake -f -N -b /home/andras/IPv6SuiteWithINET -c /home/andras/IPv6SuiteWithINET/inetconfig -n -r -X Documentation -X Etc -X Unsupported
#

# Name of target to be created (-o option)
TARGET = IPv6SuiteWithINET

# User interface (uncomment one) (-u option)
# USERIF_LIBS=$(CMDENV_LIBS)
USERIF_LIBS=$(TKENV_LIBS)

# .ned or .h include paths with -I
INCLUDE_PATH=

# misc additional object and library files to link
EXTRA_OBJS=

# object files from other directories to link with (wildcard needed to prevent "no such file *.o" errors)
EXT_DIR_OBJS=

# time stamps of other directories (used as dependency)
EXT_DIR_TSTAMPS=

# Additional libraries (-L option -l option)
LIBS=

#------------------------------------------------------------------------------
# Import generic settings from inetconfig
include inetconfig

#------------------------------------------------------------------------------

# subdirectories to recurse into
SUBDIRS=  Applications Base Examples Mobility Network NetworkInterfaces Nodes PHY Tests Transport Util World

# object files in this directory
OBJS=  

# header files generated (from msg files)
GENERATEDHEADERS= 

#------------------------------------------------------------------------------
# contents of file makefrag:
# this file automatically gets inserted into Makefiles generated by opp_makemake

# preserve default target
all: $(TARGET)

# all _m.h files must exist before we build anything, so run opp_msgc first
subdirs $(OBJS) : generateheaders

# add dependencies across directories
Network Transport NetworkInterfaces PHY Applications : Base Util
Transport NetworkInterfaces Applications : Network
Nodes : Network Transport NetworkInterfaces PHY Mobility Applications World
Examples Tests : Nodes
Examples : Tests  # this is just for convenience, can be removed

# documentation targets
DOC_DIR=Documentation

docs: doxy neddoc

doxy:
	doxygen doxy.cfg

neddoc:
	opp_neddoc -o $(DOC_DIR)/neddoc -t $(DOC_DIR)/doxy/doxytags.xml -d ../doxy *.ned *.msg $(SUBDIRS)

neddoc-without-doxy:
	opp_neddoc -o $(DOC_DIR)/neddoc *.ned *.msg $(SUBDIRS)


#------------------------------------------------------------------------------

$(TARGET): $(OBJS) subdirs Makefile .tstamp
	@# do nothing

.tstamp: $(OBJS)
	echo>.tstamp

$(OBJS) : $(GENERATEDHEADERS)


purify: $(OBJS) $(EXTRA_OBJS) $(EXT_DIR_TSTAMPS) subdirs Makefile
	purify $(CXX) $(LDFLAGS) $(OBJS) $(EXTRA_OBJS) $(EXT_DIR_OBJS) $(LIBS) -L$(OMNETPP_LIB_DIR) $(KERNEL_LIBS) $(USERIF_LIBS) $(SYS_LIBS_PURE) -o $(TARGET).pure

.PHONY: subdirs $(SUBDIRS)

subdirs: $(SUBDIRS)

Applications:
	cd Applications && $(MAKE)

Base:
	cd Base && $(MAKE)

Examples:
	cd Examples && $(MAKE)

Mobility:
	cd Mobility && $(MAKE)

Network:
	cd Network && $(MAKE)

NetworkInterfaces:
	cd NetworkInterfaces && $(MAKE)

Nodes:
	cd Nodes && $(MAKE)

PHY:
	cd PHY && $(MAKE)

Tests:
	cd Tests && $(MAKE)

Transport:
	cd Transport && $(MAKE)

Util:
	cd Util && $(MAKE)

World:
	cd World && $(MAKE)


#doc: neddoc doxy

#neddoc:
#	opp_neddoc -a

#doxy: doxy.cfg
#	doxygen doxy.cfg

generateheaders: $(GENERATEDHEADERS)
	for i in $(SUBDIRS); do (cd $$i && $(MAKE) generateheaders) || exit 1; done

clean:
	rm -f *.o *_n.cc *_n.h *_m.cc *_m.h .tstamp
	rm -f *.vec *.sca
	for i in $(SUBDIRS); do (cd $$i && $(MAKE) clean); done

depend:
	$(MAKEDEPEND) $(INCLUDE_PATH) -- *.cc
	# $(MAKEDEPEND) $(INCLUDE_PATH) -fMakefile.in -- *.cc
	for i in $(SUBDIRS); do (cd $$i && $(MAKE) depend) || exit 1; done

makefiles:
	# recreate Makefile
	opp_makemake -f  -N -b /home/andras/IPv6SuiteWithINET -c /home/andras/IPv6SuiteWithINET/inetconfig -n -r -X Documentation -X Etc -X Unsupported 
	for i in $(SUBDIRS); do (cd $$i && $(MAKE) makefiles) || exit 1; done

makefile-ins:
	# recreate Makefile.in
	opp_makemake -f -m  -N -b /home/andras/IPv6SuiteWithINET -c /home/andras/IPv6SuiteWithINET/inetconfig -n -r -X Documentation -X Etc -X Unsupported 
	for i in $(SUBDIRS); do (cd $$i && $(MAKE) makefile-ins) || exit 1; done

# "re-makemake" and "re-makemake-m" are deprecated, historic names of the above two targets
re-makemake: makefiles
re-makemake-m: makefile-ins


# DO NOT DELETE THIS LINE -- make depend depends on it.

