#!/bin/sh
root=`pwd`
MAKEMAKE=opp_makemake
OPTS="-f -N -b $root -c $root/inetconfig"

ALL_INET_INCLUDES="-I$root/Network/IPv4 -I$root/Network/IPv4d -I$root/Network/AutoRouting -I$root/Transport/TCP -I$root/Transport/UDP -I$root/NetworkInterfaces -I$root/Network/Generic -I$root/NetworkInterfaces/_802 -I$root/NetworkInterfaces/ARP -I$root/NetworkInterfaces/Ethernet -I$root/NetworkInterfaces/PPP -I$root/Applications/Generic -I$root/Applications/Ethernet -I$root/Applications/TCPApp -I$root/Applications/UDPApp -I$root/Applications/PingApp -I$root/Base -I$root/Util -I$root/Nodes/INET"
ALL_MPLS_INCLUDES="-I$root/Network/MPLS -I$root/Network/LDP -I$root/Network/RSVP_TE -I$root/Network/Scenario -I$root/Nodes/MPLS"
ALL_IPv6_INCLUDES="-I$root/Applications/Ping6 -I$root/Applications/VideoStream -I$root/Transport/UDP6 -I$root/Network/IPv6 -I$root/Network/ICMPv6 -I$root/Network/MIPv6 -I$root/Network/HMIPv6 -I$root/World -I$root/PHY -I$root/Mobility -I$root/Mobility/adHocSim -I$root/NetworkInterfaces/Ethernet6 -I$root/NetworkInterfaces/PPP6 -I$root/NetworkInterfaces/Wireless -I$root/Util/XML -I$root/Nodes/IPv6 -I$root/Util/Loki"

#ALL_MODEL_OPTS="$OPTS -w %ALL_MPLS_INET_INCLUDES%"
ALL_MODEL_OPTS="$OPTS -n"

#--------------------------------------

$MAKEMAKE $OPTS -n -r -X Documentation -X Etc -X Unsupported

(cd Applications && $MAKEMAKE $OPTS -n -r)
(cd Examples && $MAKEMAKE $OPTS -n -r -X RTP)
(cd Tests && $MAKEMAKE $OPTS -n -r -X IPv4 -X MPLS)
(cd Network && $MAKEMAKE $OPTS -n -r)
(cd NetworkInterfaces && $MAKEMAKE $OPTS -n -r -I../Util)
(cd Nodes && $MAKEMAKE $OPTS -n -r)
#FIXME remove dep on NetworkInterfaces!!!
(cd PHY && $MAKEMAKE $OPTS -n -r -I.. -I../Util -I../NetworkInterfaces/Wireless -I../NetworkInterfaces/Ethernet6)
#FIXME remove dep on NetworkInterfaces!!!
(cd Mobility && $MAKEMAKE $OPTS -n -r -I.. -I../Util -I../World -I../NetworkInterfaces -I../NetworkInterfaces/Wireless  -I../NetworkInterfaces/Ethernet6 -IadHocSim)
(cd Mobility/adHocSim && $MAKEMAKE $OPTS -n -r)

(cd Transport && $MAKEMAKE $OPTS -n -r -X RTP)
(cd Base && $MAKEMAKE $OPTS -n -r)
#FIXME Util should not depend on Mobility!
(cd Util && $MAKEMAKE $OPTS -n -r -X boost -X Topology -I. -I../Mobility -I../World -I../Base)

#---------------
#FIXME try to eliminate dep in NetworkInterfaces, Ethernet6, PPP6, Wireless, Mobility!!
(cd Network/IPv6 && $MAKEMAKE $OPTS -n -r -I../ICMPv6 -I../../NetworkInterfaces -I../../NetworkInterfaces/PPP6 -I../../NetworkInterfaces/Ethernet6 -I../../NetworkInterfaces/Wireless  -I../HMIPv6  -I../MIPv6 -I../../Util -I../../Util/Loki -I../../World -I../../Mobility -I. -I../.. -I../IPv4 -I../Generic -I../../Base)
(cd Network/ICMPv6 && $MAKEMAKE $OPTS -n -r -I../IPv6 -I../../NetworkInterfaces -I../../NetworkInterfaces/PPP6 -I../../NetworkInterfaces/Ethernet6 -I../../NetworkInterfaces/Wireless  -I../HMIPv6  -I../MIPv6 -I../../Util -I../../Util/Loki -I../../World -I../../Mobility -I. -I../.. -I../IPv4 -I../Generic -I../IPv6 -I../ICMPv6 -I../../Base)
#FIXME try to eliminate MIP dependency on HMIP and on Wireless!
(cd Network/MIPv6 && $MAKEMAKE $OPTS -n -r -I../IPv6 -I../ICMPv6 -I../HMIPv6 -I../../NetworkInterfaces -I../../NetworkInterfaces/Ethernet6 -I../../NetworkInterfaces/Wireless -I../../Util -I../../Util/Loki -I../../World -I../../PHY -I. -I../.. -I../IPv4 -I../Generic  -I../../Base)
(cd Network/HMIPv6 && $MAKEMAKE $OPTS -n -r -I../IPv6 -I../ICMPv6 -I../MIPv6 -I../../Util -I../../Util/Loki -I../../World -I../../PHY -I. -I../.. -I../IPv4 -I../Generic  -I../../Base)
(cd Network/RIP && $MAKEMAKE $OPTS -n -r)

(cd Util/Loki && $MAKEMAKE $OPTS -n -r)
(cd Util/XML && $MAKEMAKE $OPTS -n -r -I../.. -I.. -I../../Mobility -I../../Base -I../../NetworkInterfaces -I../../NetworkInterfaces/Wireless -I../../NetworkInterfaces/Ethernet6 -I../../Network/Generic -I../../Network/IPv6 -I../../Network/ICMPv6 -I../../Network/IPv4 -I../../Network/MIPv6 -I../../Network/HMIPv6)
(cd Util/Topology && $MAKEMAKE $OPTS -n -r)

#FIXME remove -IWireless from Eth!!!!! --AV
(cd NetworkInterfaces/Ethernet6 && $MAKEMAKE $OPTS -n -r -I../Wireless -I../../PHY -I.. -I../.. -I../../Util -I../../Network/IPv6 -I../../Network/ICMPv6 -I../../Network/Generic -I../../World -I../../Base)
#FIXME remove -IEthernet6 from PPP6!!!!! (dep on MACAddress) --AV
(cd NetworkInterfaces/PPP6 && $MAKEMAKE $OPTS -n -r -I../Ethernet6 -I.. -I../.. -I../../Util -I../../Network/IPv6 -I../../Network/ICMPv6 -I../../Network/Generic -I../../World -I../../PHY -I../../Base)
#FIXME sure we need -IMobility here? --AV
#FIXME remove -IPPP6 !!!!!! (dep on IPv6PPPAPInterface ???!!!!
(cd NetworkInterfaces/Wireless && $MAKEMAKE $OPTS -n -r -I../PPP6 -I.. -I../.. -I../../Util -I../Ethernet6 -I../../Network/IPv6 -I../../Network/ICMPv6 -I../../Network/Generic -I../../World -I../../Mobility -I../../PHY -I../../Base)

(cd Applications/MLD && $MAKEMAKE $OPTS -n -r)
(cd Applications/Ping6 && $MAKEMAKE $OPTS -n -r -I../.. -I../../Util -I../../Network/IPv6 -I../../Network/ICMPv6)
(cd Applications/VideoStream && $MAKEMAKE $OPTS -n -r -I../.. -I../../Util -I../../Network/IPv6 -I../../Network/ICMPv6 -I../../Transport/UDP6)

(cd Transport/UDP6 && $MAKEMAKE $OPTS -n -r -I../.. -I../../Util -I../../Network/IPv4  -I../../Network/IPv6 -I../../Network/ICMPv6)
#FIXME should not depend on all L2 stuff!
(cd World && $MAKEMAKE $OPTS -n -r -I.. -I../Util -I../Mobility -I../Network/IPv4  -I../Network/IPv6 -I../Network/ICMPv6 -I../NetworkInterfaces -I../NetworkInterfaces/Wireless -I../NetworkInterfaces/Ethernet6)
#FIXME move cc files to Ethernet6 directory!!!
(cd Nodes/IPv6 && $MAKEMAKE $OPTS -n -r -I../../Util -I../../NetworkInterfaces/Ethernet6 -I../../Network/IPv6 -I../../Network/ICMPv6 -I../../Network/IPv4)
#----


(cd Applications/Generic && $MAKEMAKE $OPTS -n -r -I../../Network/IPv4 -I../../Network/Generic -I../../Base -I../../Util)
(cd Applications/Ethernet && $MAKEMAKE $OPTS -n -r -I../../NetworkInterfaces/Ethernet -I../../Network/Generic -I../../NetworkInterfaces/_802 -I../../Base -I../../Util)
(cd Applications/PingApp && $MAKEMAKE $OPTS -n -r -I../../Network/IPv4 -I../../Base -I../../Util)
(cd Applications/TCPApp && $MAKEMAKE $OPTS -n -r -I../../Network/IPv4 -I../../Transport/TCP -I../../Base -I../../Util -I../../Network/Generic)
(cd Applications/UDPApp && $MAKEMAKE $OPTS -n -r -I../../Network/IPv4 -I../../Transport/UDP -I../../Base -I../../Util -I../../Network/Generic)

(cd Network/Generic && $MAKEMAKE $OPTS -n -r -I../../Base -I../../Util)
(cd Network/IPv4 && $MAKEMAKE $OPTS -n -r -I../../Base -I../../Util -I../Generic)
(cd Network/IPv4d && $MAKEMAKE $OPTS -n -r -I../IPv4 -I../../Base -I../../Util -I../Generic)
(cd Network/AutoRouting && $MAKEMAKE $OPTS -n -r -I../IPv4  -I../../Base -I../../Util -I../Generic)
(cd Network/MPLS && $MAKEMAKE $OPTS -n -r -I../IPv4 -I../IPv4d -I../../Base -I../../Util -I../Generic)
(cd Network/LDP && $MAKEMAKE $OPTS -n -r -I../IPv4 -I../IPv4d -I../../Transport/UDP -I../../Transport/TCP -I../MPLS -I../../Base -I../../Util -I../Generic)
(cd Network/RSVP_TE && $MAKEMAKE $OPTS -n -r -I../IPv4 -I../IPv4d -I../MPLS -I../../Base -I../../Util -I../Generic)
(cd Network/Scenario && $MAKEMAKE $OPTS -n -r -I../IPv4 -I../IPv4d -I../MPLS -I../RSVP_TE -I../../Base -I../../Util -I../Generic)

(cd NetworkInterfaces/PPP && $MAKEMAKE $OPTS -n -r -I../../Base -I../../Util -I../../Network/IPv4 -I../../Network/Generic)
(cd NetworkInterfaces/_802 && $MAKEMAKE $OPTS -n -r -I../../Base -I../../Util -I../../Network/IPv4)
(cd NetworkInterfaces/Ethernet && $MAKEMAKE $OPTS -n -r -I../../Base -I../../Util -I../_802 -I../../Network/IPv4)
(cd NetworkInterfaces/ARP && $MAKEMAKE $OPTS -n -r -I../../Base -I../../Util -I../../Network/IPv4 -I../../Network/Generic -I../_802 -I../Ethernet)

(cd Nodes/INET && $MAKEMAKE $OPTS -n -r -I../../Network/IPv4 -I../../Network/IPv4d -I../../Network/IPv4/QoS -I../../Transport/UDP -I../../NetworkInterfaces/PPP -I../../NetworkInterfaces  -I../../Applications/Generic -I../../Applications/TCPApp -I../../Applications/UDPApp -I../../Applications/PingApp -I../../Base -I../../Util)
(cd Nodes/MPLS && $MAKEMAKE $OPTS -n -r -I../../Network/IPv4 -I../../Network/IPv4d -I../../Network/IPv4/QoS -I../../Network/MPLS -I../../Network/LDP -I../../Network/RSVP_TE -I../../Transport/UDP -I../../NetworkInterfaces/PPP -I../../NetworkInterfaces  -I../../Applications/Generic -I../../Applications/TCPApp -I../../Applications/PingApp -I../INET -I../../Base -I../../Util)

(cd Transport/UDP && $MAKEMAKE $OPTS -n -r -I../../Network/IPv4 -I../../Base -I../../Util)
(cd Transport/RTP && $MAKEMAKE $OPTS -n -r -I../../Network/IPv4 -I../../Base -I../../Util)
(cd Transport/TCP && $MAKEMAKE $OPTS -n -I../../Network/IPv4 -I../../Base -I../../Util)

(cd Examples/bin && $MAKEMAKE $OPTS -w -o INET $ALL_INET_INCLUDES $ALL_IPv6_INCLUDES $ALL_MPLS_INCLUDES)

(cd Examples/Ethernet && $MAKEMAKE $OPTS -n -r)
(cd Examples/INET && $MAKEMAKE $OPTS -n -r)
(cd Examples/MPLS && $MAKEMAKE $OPTS -n -r)

(cd Examples/Ethernet/ARPTest && $MAKEMAKE $ALL_MODEL_OPTS)
(cd Examples/Ethernet/LANs && $MAKEMAKE $ALL_MODEL_OPTS)

(cd Examples/INET/NClients && $MAKEMAKE $ALL_MODEL_OPTS)
(cd Examples/INET/FlatNet && $MAKEMAKE $ALL_MODEL_OPTS)
(cd Examples/INET/KIDSNw1 && $MAKEMAKE $ALL_MODEL_OPTS)
(cd Examples/INET/Multicast && $MAKEMAKE $ALL_MODEL_OPTS)
(cd Examples/INET/RouterPerf && $MAKEMAKE $ALL_MODEL_OPTS)
(cd Examples/INET/BulkTransfer && $MAKEMAKE $ALL_MODEL_OPTS)

(cd Examples/MPLS/ldp-mpls1 && $MAKEMAKE $ALL_MODEL_OPTS)
(cd Examples/MPLS/TestTE1 && $MAKEMAKE $ALL_MODEL_OPTS -I../Tester)
(cd Examples/MPLS/TestTE2 && $MAKEMAKE $ALL_MODEL_OPTS -I../Tester)
(cd Examples/MPLS/TestTE3 && $MAKEMAKE $ALL_MODEL_OPTS -I../Tester)
(cd Examples/MPLS/TestTE4 && $MAKEMAKE $ALL_MODEL_OPTS -I../Tester)
(cd Examples/MPLS/TestTE5 && $MAKEMAKE $ALL_MODEL_OPTS -I../Tester)
(cd Examples/MPLS/TestTE6 && $MAKEMAKE $ALL_MODEL_OPTS -I../Tester)


#-----------------
(cd Examples/IPv6 && $MAKEMAKE $OPTS -n -r)
(cd Examples/IPv6/EthNetwork && $MAKEMAKE $OPTS -n -r)
(cd Examples/IPv6/HMIPv6Network && $MAKEMAKE $OPTS -n -r)
(cd Examples/IPv6/MIPv6Network && $MAKEMAKE $OPTS -n -r)
(cd Examples/IPv6/PingNetwork && $MAKEMAKE $OPTS -n -r)
(cd Examples/IPv6/TestNetwork && $MAKEMAKE $OPTS -n -r)
(cd Examples/IPv6/TunnelNet && $MAKEMAKE $OPTS -n -r)
(cd Examples/IPv6/WirelessEtherNetwork && $MAKEMAKE $OPTS -n -r)
(cd Examples/IPv6/WirelessEtherNetwork2 && $MAKEMAKE $OPTS -n -r)
(cd Examples/IPv6/WirelessEtherNetworkDual && $MAKEMAKE $OPTS -n -r)
(cd Examples/IPv6/WirelessTest && $MAKEMAKE $OPTS -n -r)
#-----------------

(cd Tests/MPLS && $MAKEMAKE $OPTS -n -r)
(cd Tests/MPLS/LDP1 && $MAKEMAKE $OPTS -w $ALL_MPLS_INCLUDES $ALL_INET_INCLUDES)
(cd Tests/NewTCP && $MAKEMAKE $OPTS -w $ALL_INET_INCLUDES)

