#!/usr/bin/env ruby
#
#  Author: Johnny Lai
#  Copyright (c) 2004 Johnny Lai
#
# =DESCRIPTION
# CMakeLists.txt generater for omnetpp type projects. Currently works with INET 
# and generates IPv6Suite's OneBigExe.cmake but should work for others too. 
#

#Pattern for doing wildcard matches of filenames recursively i.e. subdirectories too 
RECURSEDIR="**/*"

#Extension of files used for message subclassing
MSGEXT=".msg"
NEDEXT=".ned"

def traverseDirectory(dir, expression, ignore = nil)
  oldpwd = Dir.pwd
  Dir.chdir(dir)
  arr = Array.new
  Dir[expression].each {|f|
    next if ignore and f =~ Regexp.new(ignore)
    arr.push(f)
  }
  arr
ensure
  Dir.chdir(oldpwd)
end

def customCommands(dir, ignorePattern,projName)  
  
  m = traverseDirectory(dir,RECURSEDIR+MSGEXT, ignorePattern)
 
  return "" if m.size == 0
  string = "\nOPP_WRAP_MSGC(dum dum2 #{m.join("\n")}\n)\n"
	#the following will include all msg files in all subdirs
	#string += "\nOPP_WRAP_MSGC_ALL()\n"  
end

def createNedFilesList(dir, ignorePattern)  
  m = traverseDirectory(dir,RECURSEDIR+NEDEXT, ignorePattern)
  string = "#{m.join("\n")}"
  open("#{dir}/nedfiles.lst","w") {  |x|
    x.print string
  }
end

def addSourceFiles(dir, ignorePattern)
  c = traverseDirectory(dir, RECURSEDIR+".{h,cc,cpp,c}", ignorePattern)

  includeDirs = Array.new
  c.delete_if {|f| 
    header = f =~ /\.h$/     
    includeDirs.push(File.dirname(f)) if header and not includeDirs.include? File.dirname(f) 
    header
  }
  Array[c, includeDirs]
end

def addTests(dir)
  c = traverseDirectory(dir, RECURSEDIR + ".test")
  testDirs = Array.new
  c.each{ |test|
    testDirs.push(File.dirname(test)) if not testDirs.include? File.dirname(test)
  }
  testDirs
end

def writeTest(testDirs, projName)
  testDirs.each{ |d|
    open("#{d}/CMakeLists.txt","w") { |testCMake|
      testCMake.puts "LINK_LIBRARIES(#{projName} ${OPP_LIBRARIES})"
      testCMake.puts "OPP_WRAP_TEST(#{File.basename(d)})" 
    }
  }  
end

  OldRTPDeps = "|Scenario|RSVP|MPLS"

def writeCMakeList(dir, outputName, projName = nil)
  def useINETCustomIncludes(x, projName)
    x.puts("PROJECT(#{projName})\n\n") if projName and projName.length > 0

    if `hostname` =~ /hn\d/
      x.puts %|
IF(NOT WIN32)
  OPTION(ARCH64 "64 bit architecture is detected" ON)
ENDIF(NOT WIN32)

|
    end
    
    x.puts %|SET(CMAKEFILES_PATH ${PROJECT_SOURCE_DIR}/Etc/CMake)
INCLUDE(${CMAKEFILES_PATH}/Main.cmake)
|
  end
				#EtherSwitch
#Contract requires IPv4
#ARP|IPv4|TCP|FlatNetwork|Queue
  commonIgnore =
	"scripts|Scalars|Research|CMake|Unsupported|_m\.|test|Topology|PPP/|LDP|Tests|IPv4d" + OldRTPDeps
  
  sources, includes = addSourceFiles(dir, commonIgnore)    
  
  projName ||= File.basename(dir)  
  
  open("#{dir}/#{outputName}","w") {  |x|

    x.puts "# -*- CMAKE -*-"
    x.puts %{#Generated by "#{$0} #{ARGV.join(" ")}"}

    useINETCustomIncludes(x, projName) if not @customise

    createNedFilesList(dir, commonIgnore + "|Examples|Research")
    customCommandsLines = customCommands(dir, commonIgnore, projName)
    
    x.print customCommandsLines

    #It appears that these source files properties only exist in the current
    #Dir/cmakelist.txt because in subdir's cmakelist.txt cannot use the source
    #file here as it complains source does not exist unless we also set generated property in there for these files again 
    #this does not work however
    #x.print "SET_SOURCE_FILES_PROPERTIES(${GENERATED_MSGC_FILES} GENERATED PROPERTIES COMPILE_FLAGS -Wall)\n\n"

    x.print "\nSET( ", projName, "_SRCS\n"

    #necessary otherwise any subsequent SUBDIRS commands will change
    #the relative source file to an incorrect absolute path
    basepath="${PROJECT_SOURCE_DIR}/"
    
    sources.each{|c| 
      x.puts basepath + c
    }

    x.puts ")"

    xvar = ""
    xvar = <<EOF
SET_SOURCE_FILES_PROPERTIES(${#{projName}_SRCS} PROPERTIES  COMPILE_FLAGS ${COMPILER_WARNINGS})
SET(#{projName}_SRCS ${GENERATED_MSGC_FILES} ${#{projName}_SRCS})


EOF
    
    xvar.insert(0, "SET(COMPILER_WARNINGS -Wall)\n") if @customise
    x.puts xvar
    x.puts "INCLUDE_DIRECTORIES("
    includes.each{|inc|         
      x.puts basepath + inc
    }
    x.puts ")\n\n"

   if @customise

# No longer works cause simplemodules don't export their type no more in gcc output
     x.puts %|OPTION(BUILD_SHARED_LIBS "Build with shared libraries." ON)|
     x.puts(sprintf("ADD_LIBRARY(%s ${%s})\n", projName, projName + "_SRCS"))
   else
     x.puts %|INCLUDE(${CMAKEFILES_PATH}/LastInclude.cmake)|
    end
  }
end

## main

if ARGV.length < 2 then
  @customise = true
  writeCMakeList(".", "CMakeLists.txt", ARGV[0])
  exit
else
  print "Usage ",  " <source dir name> <Project Name>\n", \
  " where [source dir] is where CMakeLists.txt will be generated for\n", \
  "Generated in current working directory"

  projName = ARGV[1]
	#customise used to be for making OneBigStaticExe.cmake except forgot how to generate sourcelist 
  @customise = false
  outname = @customise ? "OneBigStaticExe.cmake" : "CMakeLists.txt"
  writeCMakeList(ARGV[0], outname, projName)
end
