# -*- CMAKE -*-
INCLUDE(${CMAKEFILES_PATH}/FindBoost.cmake)

IF(LIBCWD_DEBUG)
  INCLUDE(${CMAKEFILES_PATH}/FindLibcwd.cmake)

  IF(LIBCWD_FOUND)
    ADD_DEFINITIONS( -I${LIBCWD_INCLUDE_DIR} )
  ELSE(LIBCWD_FOUND)
    MESSAGE(SEND_ERROR "Cannot find libcw/debug.h. Are you sure libcwd is installed?")
  ENDIF(LIBCWD_FOUND)
ENDIF(LIBCWD_DEBUG)

INCLUDE(${CMAKEFILES_PATH}/FindOmnet.cmake)
IF(NOT HAS_OPP)
  MESSAGE(FATAL_ERROR "OMNeT++ not detected completely for some reason")
ENDIF(NOT HAS_OPP)

IF(USE_XMLWRAPP)
  SET(USE_XMLWRAPP_DEFINE "USE_XMLWRAPP")
  ADD_DEFINITIONS(-D${USE_XMLWRAPP_DEFINE})

  INCLUDE(${CMAKEFILES_PATH}/FindXmlwrapp.cmake)
  IF(XMLWRAPP_FOUND)
    ADD_DEFINITIONS( ${XMLWRAPP_CXX_FLAGS} )
  ELSE(XMLWRAPP_FOUND)
    MESSAGE(FATAL_ERROR "Cannot find program xmlwrapp-config. Is xmlwrapp installed?")
  ENDIF(XMLWRAPP_FOUND)
ENDIF(USE_XMLWRAPP)
IF(USE_XERCES)
  INCLUDE(${CMAKEFILES_PATH}/FindXerces.cmake)
ENDIF(USE_XERCES)

IF(BUILD_UNITTESTS)
  INCLUDE(${CMAKEFILES_PATH}/FindCppUnit.cmake)

  IF(CPPUNIT_FOUND)
    ADD_DEFINITIONS(${CPPUNIT_CXX_FLAGS})
  ELSE(CPPUNIT_FOUND)
    MESSAGE(SEND_ERROR "Cannot find program cppunit-config. Is cppunit installed?")
  ENDIF(CPPUNIT_FOUND)
ENDIF(BUILD_UNITTESTS)

IF(NOT BUILD_SHARED_LIBS)
#Stop it from adding -rpath for static libs
  SET(CMAKE_SKIP_RPATH ON)
  #a -u for every ctor with weak linkage (all csimplemodules at least) :(
  #-static prevents .so linking
  #SET(CMAKE_EXE_LINKER_FLAGS "-static -Ur -u _ZN14WorldProcessorC1EPKcP7cModulej")
  SET(CMAKE_MODULE_LINKER_FLAGS -static -r)
  SET(CMAKE_CXX_FLAGS -static)
ENDIF(NOT BUILD_SHARED_LIBS)

IF(CMAKE_CXX_COMPILER MATCHES "cxx")
  ADD_DEFINITIONS(-DCXX)
ENDIF(CMAKE_CXX_COMPILER MATCHES "cxx")

MARK_AS_ADVANCED(FORCE DART_ROOT ScpCommand)
MARK_AS_ADVANCED(CMAKE_BUILD_TYPE EXECUTABLE_OUTPUT_PATH LIBRARY_OUTPUT_PATH)
