FIND_PROGRAM(XML_CONFIG xml2-config 
	$ENV{HOME}/bin 
	$ENV{HOME}/lib/bin
)

IF(XML_CONFIG)
  SET(XML_CXX_FLAGS "`${XML_CONFIG} --cflags`")
  SET(XML_LIBRARY "`${XML_CONFIG} --libs`")
  MARK_AS_ADVANCED(XML_CXX_FLAGS XML_LIBRARY)
  SET(XML_FOUND "YES")
ENDIF(XML_CONFIG)

IF(NOT WIN32)
IF(NOT XML_FOUND)
  FIND_LIBRARY(EXPAT_LIBRARY expat
    PATHS /usr/lib /usr/local/lib
    )
  SET(XML_LIBRARY ${EXPAT_LIBRARY})
  MARK_AS_ADVANCED(FORCE EXPAT_LIBRARY)
ENDIF(NOT XML_FOUND)
ELSE(NOT WIN32)
#libxml2 included as part of windows omnet++ package
SET(XML_LIBRARY libxml2)
ENDIF(NOT WIN32)
