FIND_PROGRAM(CPPUNIT_CONFIG cppunit-config 
	$ENV{HOME}/bin 
	$ENV{HOME}/lib/bin
)

IF(CPPUNIT_CONFIG)
  SET(CPPUNIT_CXX_FLAGS "`${CPPUNIT_CONFIG} --cflags`")
  SET(CPPUNIT_LIBRARY "`${CPPUNIT_CONFIG} --libs`")
  MARK_AS_ADVANCED(CPPUNIT_CXX_FLAGS CPPUNIT_LIBRARY)
  SET(CPPUNIT_FOUND "YES")
ENDIF(CPPUNIT_CONFIG)
