FIND_PROGRAM(XMLWRAPP_CONFIG xmlwrapp-config 
	$ENV{HOME}/bin 
	$ENV{HOME}/lib/bin
)

IF(XMLWRAPP_CONFIG)
  SET(XMLWRAPP_CXX_FLAGS "`${XMLWRAPP_CONFIG} --cflags`")
  SET(XMLWRAPP_LIBRARY "`${XMLWRAPP_CONFIG} --libs`")
  MARK_AS_ADVANCED(XMLWRAPP_CXX_FLAGS XMLWRAPP_LIBRARY)
  SET(XMLWRAPP_FOUND "YES")
ENDIF(XMLWRAPP_CONFIG)
