# -*- CMAKE -*-


SET(MISCDIR ${PROJECT_SOURCE_DIR}/Etc)
SET(SCRIPTDIR ${MISCDIR}/scripts)
SET(BINMISCDIR ${PROJECT_BINARY_DIR}/Etc)
SET(BINSCRIPTDIR ${BINMISCDIR}/scripts)
SET(DUMMY_SOURCE ${BINMISCDIR}/dummy.cc)

STRING(COMPARE NOTEQUAL ${PROJECT_SOURCE_DIR} ${PROJECT_BINARY_DIR} OUTOFSOURCE)

INCLUDE(${CMAKEFILES_PATH}/Options.cmake)

INCLUDE(${CMAKEFILES_PATH}/IntelICCOptions.cmake)

#INCLUDE(${CMAKE_ROOT}/Modules/Dart.cmake)

INCLUDE(${CMAKEFILES_PATH}/Configure.cmake)

INCLUDE(${CMAKEFILES_PATH}/Macros.cmake)

IF(OUTOFSOURCE)
#Create Research, Etc, boost links 
  ADD_CUSTOM_TARGET( prebuild ALL rm -fr  ${PROJECT_BINARY_DIR}/Etc ${PROJECT_BINARY_DIR}/Research ${PROJECT_BINARY_DIR}/boost 
		   COMMAND ln -sf ${PROJECT_SOURCE_DIR}/Etc ${PROJECT_BINARY_DIR}/Etc
		   COMMAND ln -sf ${PROJECT_SOURCE_DIR}/Research ${PROJECT_BINARY_DIR}/Research
		   COMMAND ln -sf ${PROJECT_SOURCE_DIR}/boost ${PROJECT_BINARY_DIR}/boost

		   WORKING_DIRECTORY ${PROJECT_BINARY_DIR})
ENDIF(OUTOFSOURCE)

