#! /bin/sh

#DEST=${PWD}
#DEST="${HOME}/data"
DEST="/short/ewu/data"
#DEST="/short_term/ewu/data"

if [ $# -ne 2 ]
then
  echo "Please enter the name of scenario and the number of runs required (eg. <name> <no. of runs>)" 
  exit 1
fi

let "numberOfSeeds=${2}"
setRun=1

cp SimulMove2.ini SimulMove2_${1}.ini
(cd ${DEST}; mkdir MN-MNComms_${1};)

seedtool g 1 10000000 $numberOfSeeds > seeds.txt
for seed in `cat seeds.txt`;
do
     cat <<EOF >>SimulMove2_${1}.ini
[Run ${setRun}]
mipv6NetworkSimulMove2.*.IPv6routingFile = xmldoc("MIPv6NetworkSimulMove2.xml")
network = mipv6NetworkSimulMove2
output-vector-file = MN-MNComms_${1}-${setRun}.vec
seed_lcg32 = ${seed}
include ../../../Etc/default.ini
EOF
     cat <<EOF >>SimulMove2_${1}-run${setRun}
#! /bin/sh
#PBS -N ${1}
$PWD/../../../bin/INET -u Cmdenv -f $PWD/SimulMove2_${1}.ini -r ${setRun}
mv $PWD/MN-MNComms_${1}-${setRun}.vec ${DEST}/MN-MNComms_${1}
EOF
     chmod 744 SimulMove2_${1}-run${setRun}
     qsub SimulMove2_${1}-run${setRun}
     rm SimulMove2_${1}-run${setRun}
     setRun=`expr $setRun + 1`
done
