#! /bin/sh

#DEST=${PWD}
#DEST="${HOME}/data"
DEST="/short/ewu/data"
#DEST="/short_term/ewu/data"

Queue=""
#Queue="-q run_1_hour"

if [ $# -ne 5 ]
then
  echo ""
  echo "multiCNspeed MN CN_MIN CN_MAX SIG RUNS" 
  echo " "
  echo "Description -"
  echo " "
  echo "multiCNspeed copies SimulMove2.ini into multiple .ini files,"
  echo "and creates batches files for each of the scenarios, according"
  echo "to the MN's speed, ranges of CN speed increments, signaling" 
  echo "method, and total number of runs. It then runs the simulation"
  echo "through PBS to distribute the jobs onto available nodes"
  echo " "
  echo "Arguments - "
  echo " "
  echo "   MN - MN's speed incremet"
  echo "   CNMIN - CN's minimum speed increment"
  echo "   CNMAX - CN's maximum speed increment"
  echo "   SIG - Signaling method"
  echo "   RUNS Number of runs"
  echo " "
  echo "Example - "
  echo " "
  echo "multiCNspeed 2 0 9 Indir 25"
  echo ""
  exit 1
fi

let "numberOfSeeds=${5}"

# for loop here

for i in `seq ${2} ${3}`;
do

xsltproc -o MIPv6NetworkSimulMove2_MN${1}msCN${i}ms${4}.xml --stringparam signaling ${4} --stringparam mnSpeed ${1} --stringparam cnSpeed ${i} signalingScenario.xsl MIPv6NetworkSimulMove2.xml

cp SimulMove2.ini SimulMove2_MN${1}msCN${i}ms${4}.ini
(cd ${DEST}; mkdir MN-MNComms_MN${1}msCN${i}ms${4};)

seedtool g 1 10000000 $numberOfSeeds > seeds.txt

setRun=1
for seed in `cat seeds.txt`;
do
     cat <<EOF >>SimulMove2_MN${1}msCN${i}ms${4}.ini
[Run ${setRun}]
mipv6NetworkSimulMove2.*.IPv6routingFile = xmldoc("MIPv6NetworkSimulMove2_MN${1}msCN${i}ms${4}.xml")
network = mipv6NetworkSimulMove2
output-vector-file = MN-MNComms_MN${1}msCN${i}ms${4}-${setRun}.vec
seed_lcg32 = ${seed}
include ../../../Etc/default.ini
EOF
     cat <<EOF >>SimulMove2_MN${1}msCN${i}ms${4}-run${setRun}
#! /bin/sh
#PBS -k n
#PBS -N M${1}C${i}${4}${setRun}
#PBS -l walltime=00:20:00
$PWD/../../../bin/INET -u Cmdenv -f $PWD/SimulMove2_MN${1}msCN${i}ms${4}.ini -r ${setRun}
mv $PWD/MN-MNComms_MN${1}msCN${i}ms${4}-${setRun}.vec ${DEST}/MN-MNComms_MN${1}msCN${i}ms${4}
rm MIPv6NetworkSimulMove2_MN${1}msCN${i}ms${4}.xml
EOF
     chmod 744 SimulMove2_MN${1}msCN${i}ms${4}-run${setRun}
     qsub ${Queue} SimulMove2_MN${1}msCN${i}ms${4}-run${setRun}
     rm SimulMove2_MN${1}msCN${i}ms${4}-run${setRun}
     setRun=`expr $setRun + 1`
done # end runs

done # end CN speed increment
