#! /bin/sh

#DEST="~/data"
DEST="/short/ewu/data"

if [ $# -ne 3 ]
then
  echo "Please enter the name of scenario and the number of runs required (eg. <name> <no. of runs>)" 
  exit 1
fi

let "numberOfSeeds=${3}"

# for loop here

for i in `seq 0 9`;
do

cp SimulMove2.ini SimulMove2_MN${1}CN${i}ms${2}.ini
(cd ${DEST}; mkdir MN-MNComms_MN${1}CN${i}ms${2};)

seedtool g 1 10000000 $numberOfSeeds > seeds.txt

setRun=1
for seed in `cat seeds.txt`;
do
     cat <<EOF >>SimulMove2_MN${1}CN${i}ms${2}.ini
[Run ${setRun}]
mipv6NetworkSimulMove2.*.IPv6routingFile = xmldoc("MIPv6NetworkSimulMove2_CN${i}ms.xml")
network = mipv6NetworkSimulMove2
output-vector-file = MN-MNComms_MN${1}CN${i}ms${2}-${setRun}.vec
seed_lcg32 = ${seed}
include ../../../Etc/default.ini
EOF
     cat <<EOF >>SimulMove2_MN${1}CN${i}ms${2}-run${setRun}
#! /bin/sh
#PBS -S /bin/sh
#PBS -N ${1}
$PWD/../../../bin/INET -u Cmdenv -f $PWD/SimulMove2_MN${1}CN${i}ms${2}.ini -r ${setRun}
mv $PWD/MN-MNComms_MN${1}CN${i}ms${2}-${setRun}.vec ${DEST}/MN-MNComms_MN${1}CN${i}ms${2}
EOF
     chmod 744 SimulMove2_MN${1}CN${i}ms${2}-run${setRun}
     qsub SimulMove2_MN${1}CN${i}ms${2}-run${setRun}
     rm SimulMove2_MN${1}CN${i}ms${2}-run${setRun}
     setRun=`expr $setRun + 1`
done # end runs

done # end CN speed increment
